### ISSUE TITLE
Actividad 4 mapa mental 

### ISSUE THREAD

**Issue by Vanessacruzortiz** [SistemasTecTlaxiaco/actividad-4-mapa-mental-Vanessacruzortiz#1]
[Mapa mental Actividad 1 vanessa cruz ortiz.pdf](https://github.com/SistemasTecTlaxiaco/actividad-4-mapa-mental-Vanessacruzortiz/files/9620749/Mapa.mental.Actividad.1.vanessa.cruz.ortiz.pdf)

**Comment by Blanca-estela-valerio-rivero** [comment]
Tiene 18  de 20

**Comment by josealfredo79** [comment]
Bien hecho y revisado
